# Generated by Django 5.0 on 2024-01-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/animes/%Y/%m/%d', verbose_name='Picture'),
        ),
    ]
